sudo: false
rvm:
  - 2.3.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database railsbridgemtl_test' -U postgres
script:
  - RAILS_ENV=test bin/rake --trace db:migrate
  - bundle exec rspec spec
env:
  - DB=postgresql
