# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6e4638c7044f7e020ebfd197445f53d03636dbf4fdd8d1771a69c399355de017b11bfdd0b5f2f1ff2430a1debd7a213cc1490dd89f7c6b3a2ddf966b6dc149b

test:
  secret_key_base: 8bb70f56819bbfcea8bdd25cf8b0f077c1e5c621406bea05a137516288f28d70c34ba7124cc0de392d879c5707d727973e00ab71aa53a8e7637f2f8e30554115

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
